language: ruby
rvm:
  - 2.6
before_install:
  - gem install -v 2.0.1 --no-document bundler
scripts:
  - make build
deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
