language: ruby
rvm:
  - 2.6

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

script: make build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  fqdn: apidocs.nobitex.ir
  on:
    branch: master
